// ─── Helpers ─────────────────────────────────────────────────────────────────
export const generateMembershipId = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  const prefix = 'BRB'
  const suffix = Array.from({ length: 6 }, () => chars[Math.floor(Math.random() * chars.length)]).join('')
  return `${prefix}-${suffix}`
}

// ─── Users ────────────────────────────────────────────────────────────────────
export const mockUsers = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@barberos.com',
    password: 'admin123',
    role: 'admin',
    phone: '0917-000-0001',
    stamps: 0,
    totalVisits: 0,
    membershipId: 'BRB-ADMIN0',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 2,
    name: 'Juan dela Cruz',
    email: 'juan@email.com',
    password: 'password123',
    role: 'customer',
    phone: '0917-555-1234',
    stamps: 7,
    totalVisits: 7,
    membershipId: 'BRB-JDC001',
    avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
    createdAt: '2024-02-15T00:00:00.000Z',
  },
  {
    id: 3,
    name: 'Miguel Santos',
    email: 'miguel@email.com',
    password: 'password123',
    role: 'customer',
    phone: '0916-777-9876',
    stamps: 12,
    totalVisits: 14,
    membershipId: 'BRB-MIG002',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    createdAt: '2024-03-10T00:00:00.000Z',
  },
  {
    id: 4,
    name: 'Carlos Reyes',
    email: 'carlos@email.com',
    password: 'password123',
    role: 'customer',
    phone: '0915-444-3210',
    stamps: 3,
    totalVisits: 3,
    membershipId: 'BRB-CAR003',
    avatar: 'https://randomuser.me/api/portraits/men/35.jpg',
    createdAt: '2024-04-20T00:00:00.000Z',
  },
]

// ─── Barbers ──────────────────────────────────────────────────────────────────
export const mockBarbers = [
  {
    id: 1,
    name: 'Marcus Rodriguez',
    specialty: 'Classic & Modern Cuts',
    experience: '8 years',
    rating: 4.9,
    reviewCount: 247,
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    bio: 'Master of precision cuts and classic barbering techniques. Marcus brings over 8 years of expertise in crafting the perfect gentleman\'s look — from timeless classics to modern fades.',
    services: [1, 2, 5],
    schedule: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '20:00' },
      saturday: { open: '08:00', close: '17:00' },
      sunday: null,
    },
    social: { instagram: '@marcus_cuts', facebook: 'MarcusCuts' },
    active: true,
  },
  {
    id: 2,
    name: 'Diego Morales',
    specialty: 'Fades & Skin Tapers',
    experience: '6 years',
    rating: 4.8,
    reviewCount: 193,
    image: 'https://randomuser.me/api/portraits/men/44.jpg',
    bio: 'Diego is renowned for his flawless fade technique and skin taper mastery. His eye for detail and precision make every cut a work of art that clients come back for again and again.',
    services: [1, 2, 3],
    schedule: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: null,
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    social: { instagram: '@diego_fades', facebook: 'DiegoMoralesCuts' },
    active: true,
  },
  {
    id: 3,
    name: 'Rafael Dela Torre',
    specialty: 'Grooming & Facial Treatments',
    experience: '10 years',
    rating: 4.9,
    reviewCount: 312,
    image: 'https://randomuser.me/api/portraits/men/55.jpg',
    bio: 'Rafael combines a decade of barbering with extensive skincare expertise. Specializing in premium grooming packages and facial treatments, he delivers a full-service luxury experience.',
    services: [1, 4, 5, 6],
    schedule: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    social: { instagram: '@rafael_groom', facebook: 'RafaelDelaForre' },
    active: true,
  },
  {
    id: 4,
    name: 'Leon Bautista',
    specialty: 'Hair Coloring & Treatments',
    experience: '5 years',
    rating: 4.7,
    reviewCount: 128,
    image: 'https://randomuser.me/api/portraits/men/67.jpg',
    bio: 'Leon is a creative colorist and treatment specialist. He stays at the forefront of hair coloring trends, delivering bold transformations and restorative treatments that revitalize every strand.',
    services: [1, 3, 6],
    schedule: {
      monday: null,
      tuesday: { open: '11:00', close: '20:00' },
      wednesday: { open: '11:00', close: '20:00' },
      thursday: { open: '11:00', close: '20:00' },
      friday: { open: '11:00', close: '20:00' },
      saturday: { open: '10:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    social: { instagram: '@leon_color', facebook: 'LeonBautistaHair' },
    active: true,
  },
]

// ─── Services ─────────────────────────────────────────────────────────────────
export const mockServices = [
  {
    id: 1,
    name: 'Classic Haircut',
    description: 'Precision scissor and clipper cut tailored to your preferred style. Includes shampoo, cut, and blow-dry for a polished finish.',
    duration: 45,
    price: 350,
    category: 'hair',
    gradient: 'from-amber-900 to-zinc-900',
    icon: '✂️',
    available: true,
  },
  {
    id: 2,
    name: 'Beard Trim & Shape',
    description: 'Expert beard sculpting and shaping with premium oils and balms. Defines your jawline and keeps your beard looking impeccably groomed.',
    duration: 30,
    price: 250,
    category: 'beard',
    gradient: 'from-stone-800 to-zinc-900',
    icon: '🪒',
    available: true,
  },
  {
    id: 3,
    name: 'Hair Coloring',
    description: 'Full hair coloring service using premium ammonia-free dye. Includes consultation, application, processing, and finishing style.',
    duration: 90,
    price: 800,
    category: 'hair',
    gradient: 'from-indigo-900 to-zinc-900',
    icon: '🎨',
    available: true,
  },
  {
    id: 4,
    name: 'Luxury Facial',
    description: 'Deep-cleansing facial with exfoliation, steam, mask treatment, and moisturizer. Leaves your skin refreshed and revitalized.',
    duration: 60,
    price: 650,
    category: 'skin',
    gradient: 'from-emerald-900 to-zinc-900',
    icon: '✨',
    available: true,
  },
  {
    id: 5,
    name: 'Hot Towel Shave',
    description: 'Traditional straight-razor shave with hot towel preparation, pre-shave oil, and premium shaving cream for the ultimate close shave.',
    duration: 45,
    price: 450,
    category: 'shave',
    gradient: 'from-rose-900 to-zinc-900',
    icon: '🔥',
    available: true,
  },
  {
    id: 6,
    name: 'Hair Treatment',
    description: 'Intensive keratin or protein treatment to restore damaged hair. Deeply nourishes each strand for a healthier, shinier result.',
    duration: 75,
    price: 750,
    category: 'hair',
    gradient: 'from-teal-900 to-zinc-900',
    icon: '💆',
    available: true,
  },
]

// ─── Rewards ──────────────────────────────────────────────────────────────────
export const mockRewards = [
  {
    id: 1,
    stamps: 5,
    name: 'Free Classic Haircut',
    description: 'Redeem for one complimentary Classic Haircut with any barber of your choice.',
    type: 'service',
    icon: '✂️',
    value: 350,
  },
  {
    id: 2,
    stamps: 10,
    name: 'Free Luxury Facial',
    description: 'Treat yourself to a complimentary full Luxury Facial treatment.',
    type: 'service',
    icon: '✨',
    value: 650,
  },
  {
    id: 3,
    stamps: 15,
    name: 'Premium Grooming Package',
    description: 'The ultimate package: Haircut + Beard Trim + Hot Towel Shave + Facial. The full gentleman experience.',
    type: 'package',
    icon: '👑',
    value: 1500,
  },
  {
    id: 4,
    stamps: 20,
    name: 'VIP Membership Month',
    description: '30 days of VIP membership with 20% off all services and priority booking.',
    type: 'membership',
    icon: '⭐',
    value: 2000,
  },
]

// ─── Appointments ─────────────────────────────────────────────────────────────
export const mockAppointments = [
  {
    id: 'APT-001',
    userId: 2,
    userName: 'Juan dela Cruz',
    userEmail: 'juan@email.com',
    barberId: 1,
    barberName: 'Marcus Rodriguez',
    serviceId: 1,
    serviceName: 'Classic Haircut',
    servicePrice: 350,
    date: '2026-05-20',
    timeSlot: '10:00',
    status: 'confirmed',
    paymentMethod: 'gcash',
    paymentProof: 'proof_001.jpg',
    createdAt: '2026-05-14T08:00:00.000Z',
  },
  {
    id: 'APT-002',
    userId: 2,
    userName: 'Juan dela Cruz',
    userEmail: 'juan@email.com',
    barberId: 2,
    barberName: 'Diego Morales',
    serviceId: 2,
    serviceName: 'Beard Trim & Shape',
    servicePrice: 250,
    date: '2026-04-15',
    timeSlot: '14:00',
    status: 'completed',
    paymentMethod: 'gcash',
    paymentProof: 'proof_002.jpg',
    createdAt: '2026-04-10T10:00:00.000Z',
  },
  {
    id: 'APT-003',
    userId: 3,
    userName: 'Miguel Santos',
    userEmail: 'miguel@email.com',
    barberId: 3,
    barberName: 'Rafael Dela Torre',
    serviceId: 4,
    serviceName: 'Luxury Facial',
    servicePrice: 650,
    date: '2026-05-21',
    timeSlot: '11:00',
    status: 'pending_payment',
    paymentMethod: null,
    paymentProof: null,
    createdAt: '2026-05-14T09:00:00.000Z',
  },
  {
    id: 'APT-004',
    userId: 4,
    userName: 'Carlos Reyes',
    userEmail: 'carlos@email.com',
    barberId: 1,
    barberName: 'Marcus Rodriguez',
    serviceId: 5,
    serviceName: 'Hot Towel Shave',
    servicePrice: 450,
    date: '2026-05-22',
    timeSlot: '09:30',
    status: 'payment_submitted',
    paymentMethod: 'bank_transfer',
    paymentProof: 'proof_004.jpg',
    createdAt: '2026-05-13T14:00:00.000Z',
  },
  {
    id: 'APT-005',
    userId: 3,
    userName: 'Miguel Santos',
    userEmail: 'miguel@email.com',
    barberId: 4,
    barberName: 'Leon Bautista',
    serviceId: 3,
    serviceName: 'Hair Coloring',
    servicePrice: 800,
    date: '2026-04-28',
    timeSlot: '13:00',
    status: 'completed',
    paymentMethod: 'gcash',
    paymentProof: 'proof_005.jpg',
    createdAt: '2026-04-20T11:00:00.000Z',
  },
  {
    id: 'APT-006',
    userId: 2,
    userName: 'Juan dela Cruz',
    userEmail: 'juan@email.com',
    barberId: 3,
    barberName: 'Rafael Dela Torre',
    serviceId: 6,
    serviceName: 'Hair Treatment',
    servicePrice: 750,
    date: '2026-03-10',
    timeSlot: '16:00',
    status: 'completed',
    paymentMethod: 'bank_transfer',
    paymentProof: 'proof_006.jpg',
    createdAt: '2026-03-05T10:00:00.000Z',
  },
]

// ─── Redemptions ──────────────────────────────────────────────────────────────
export const mockRedemptions = [
  {
    id: 'RDM-001',
    userId: 3,
    rewardId: 1,
    rewardName: 'Free Classic Haircut',
    redeemedAt: '2026-04-01T10:00:00.000Z',
    status: 'used',
  },
]

// ─── Analytics (static mock for dashboard) ───────────────────────────────────
export const mockAnalytics = {
  totalRevenue: 28450,
  totalBookings: 86,
  totalCustomers: 54,
  todayBookings: 4,
  revenueByMonth: [
    { month: 'Jan', revenue: 3200 },
    { month: 'Feb', revenue: 4100 },
    { month: 'Mar', revenue: 3800 },
    { month: 'Apr', revenue: 5200 },
    { month: 'May', revenue: 4950 },
  ],
  bookingsByService: [
    { name: 'Classic Haircut', value: 34 },
    { name: 'Beard Trim', value: 22 },
    { name: 'Hair Coloring', value: 11 },
    { name: 'Luxury Facial', value: 9 },
    { name: 'Hot Towel Shave', value: 7 },
    { name: 'Hair Treatment', value: 3 },
  ],
  topBarbers: [
    { name: 'Rafael Dela Torre', bookings: 28, revenue: 9800 },
    { name: 'Marcus Rodriguez', bookings: 24, revenue: 8400 },
    { name: 'Diego Morales', bookings: 20, revenue: 7000 },
    { name: 'Leon Bautista', bookings: 14, revenue: 5200 },
  ],
}
